import { ClerkProvider } from "@clerk/nextjs";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../styles/globals.css";
import Navbar from "./_components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Movie Goers",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <main className="bg-background text-foreground">
            <header>
              <Navbar />
            </header>
            <div className="flex-1 flex-grow">{children}</div>
          </main>
        </body>
      </html>
    </ClerkProvider>
  );
};

export default RootLayout;
